### ISSUE TITLE
Lost files

### ISSUE THREAD

**Issue by AlexPAV** [brookshi/123#1]
Lost files in project:
Utils/Urls.cs
Authorization/LoginKeyProvider.cs

**Comment by brookshi** [comment]
Yes,I know this. These two files are access authorization of ZhiHu. I cracked it. 
I may get into trouble if upload these files. So..may over time will be updated.
Another project [UWP_ZhiHuRiBao](https://github.com/brookshi/UWP_ZhiHuRiBao) doesn't have this problem, you can try it :)

**Comment by AlexPAV** [comment]
Ok. Thanks for your feedback
